### ISSUE TITLE
ERROR: "`appcast` stanza is deprecated! Use the `livecheck` stanza instead"

### ISSUE THREAD

**Issue by Dentrax** [devhubapp/homebrew-devhub#5]
I'm not sure if this project still maintaining but dropping the issue here for awareness:

`brew update`:

```
Warning: Calling the `appcast` stanza is deprecated! Use the `livecheck` stanza instead.
Please report this issue to the devhubapp/devhub tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/devhubapp/homebrew-devhub/Casks/devhub.rb:6
```

**Comment by rrubio** [comment]
+1

**Comment by ajsobrino96** [comment]
+1

**Comment by Frabanz** [comment]
Same issue:

`brew upgrade`

```
Warning: Calling the `appcast` stanza is deprecated! Use the `livecheck` stanza instead.
Please report this issue to the adoptopenjdk/openjdk tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/adoptopenjdk/homebrew-openjdk/Casks/adoptopenjdk14.rb:8
```

Edit:

This resolved the issue for me:

```
brew uninstall --cask adoptopenjdk14
brew untap AdoptOpenJDK/openjdk
brew install --cask temurin
```

[Read more](https://github.com/AdoptOpenJDK/homebrew-openjdk)

**Comment by kessyus** [comment]
Same here.

**Comment by Eji4h** [comment]
+1

**Comment by sekomer** [comment]
+1

```
➜  ~ brew update
Already up-to-date.
➜  ~
➜  ~
➜  ~ brew upgrade
Warning: Calling the `appcast` stanza is deprecated! Use the `livecheck` stanza instead.
Please report this issue to the adoptopenjdk/openjdk tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/adoptopenjdk/homebrew-openjdk/Casks/adoptopenjdk8.rb:9
```

**Comment by corasan** [comment]
I fixed this by doing
```bash
brew uninstall --cask adoptopenjdk11
brew untap AdoptOpenJDK/openjdk
brew install --cask temurin
```

Source: https://github.com/AdoptOpenJDK/homebrew-openjdk

**Comment by Frabanz** [comment]
This resolved the issue for me:

```
brew uninstall --cask adoptopenjdk14
brew untap AdoptOpenJDK/openjdk
brew install --cask temurin
```

[Read more](https://github.com/AdoptOpenJDK/homebrew-openjdk)

**Comment by dpagano** [comment]
Any idea what to do if the error already comes up when trying to uninstall adoptopenjdk?

**EDIT:**
brew has been fixed and updating to the latest version fixed the issue for me.

**Comment by liamd101** [comment]
+1. tried the proposed solution and got this:
```
➜  ~ brew uninstall --cask adoptopenjdk11
brew untap AdoptOpenJDK/openjdk
brew install --cask temurin
Warning: Calling the `appcast` stanza is deprecated! Use the `livecheck` stanza instead.
Please report this issue to the adoptopenjdk/openjdk tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/adoptopenjdk/homebrew-openjdk/Casks/adoptopenjdk11.rb:9

Warning: Calling the `appcast` stanza is deprecated! Use the `livecheck` stanza instead.
Please report this issue to the adoptopenjdk/openjdk tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/adoptopenjdk/homebrew-openjdk/Casks/adoptopenjdk8.rb:9

Error: Cask 'adoptopenjdk11' is not installed.
Warning: Calling the `appcast` stanza is deprecated! Use the `livecheck` stanza instead.
Please report this issue to the adoptopenjdk/openjdk tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/adoptopenjdk/homebrew-openjdk/Casks/adoptopenjdk8.rb:9

Error: Refusing to untap adoptopenjdk/openjdk because it contains the following installed formulae or casks:
adoptopenjdk8
Warning: Not upgrading temurin, the latest version is already installed
```

**Comment by mattiacantalu** [comment]
> Same issue:
> 
> `brew upgrade`
> 
> ```
> Warning: Calling the `appcast` stanza is deprecated! Use the `livecheck` stanza instead.
> Please report this issue to the adoptopenjdk/openjdk tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
>   /usr/local/Homebrew/Library/Taps/adoptopenjdk/homebrew-openjdk/Casks/adoptopenjdk14.rb:8
> ```
> 
> Edit:
> 
> This resolved the issue for me:
> 
> ```
> brew uninstall --cask adoptopenjdk14
> brew untap AdoptOpenJDK/openjdk
> brew install --cask temurin
> ```
> 
> [Read more](https://github.com/AdoptOpenJDK/homebrew-openjdk)

You saved my day! Thanks :)

**Comment by sunghoonchung** [comment]
Comment out the appcast line: This means adding // to the beginning of the line so that it is ignored by the program.

ex) vi /usr/local/Homebrew/Library/Taps/adoptopenjdk/homebrew-openjdk/Casks/adoptopenjdk11.rb
...
  \# appcast "https://github.com/AdoptOpenJDK/openjdk#{version.major}-binaries/releases/latest" << Comment out
  name "AdoptOpenJDK 11"
...

**Comment by ClementRichard13** [comment]
ca a l'air d'avoir fonctionné 👍 
clementrichard@macbook-pro-de-clement ~ % brew install --cask temurin
==> Downloading https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.2%2B13/OpenJDK21U-jdk_aarch64_mac_hot
Already downloaded: /Users/clementrichard/Library/Caches/Homebrew/downloads/ab5e476b66f1d0a78d10d130042845aaa0b0cf7b0a4200db3134b27d065d3495--OpenJDK21U-jdk_aarch64_mac_hotspot_21.0.2_13.pkg
==> Installing Cask temurin
==> Running installer for temurin with sudo; the password may be necessary.
Password:
installer: Package name is Eclipse Temurin
installer: Installing at base path /
installer: The install was successful.
🍺  temurin was successfully installed!
clementrichard@macbook-pro-de-clement ~ %

**Comment by JeroenSchmidt** [comment]
`brew uninstall --cask adoptopenjdk14` & `brew upgrade` would not not work for me because it would error out with `Calling the 'appcast' stanza is deprecated!`.

`brew untap adoptopenjdk/openjdk` fixed things for me.
